### ISSUE TITLE
大佬您好，请问有没有融合好的效果图展示呀

### ISSUE THREAD

**Issue by Wohaizainuli** [masskx/PSA-Fusion#1]

**Comment by masskx** [comment]
您好，我不是大佬，我整理一下晚点上传，我第一次做图像融合，感觉效果其实一般 
![融合结果r](https://github.com/masskx/PSA-Fusion/assets/92963802/bcdbd0ca-31b2-4dcd-a125-2b3c09726137)

**Comment by masskx** [comment]
这是白天的图像转的灰度图，但是用夜晚的效果就还行，白天这个场景效果不好，意义也不大

**Comment by Wohaizainuli** [comment]
感谢感谢，可以加您个联系方式吗

**Comment by masskx** [comment]
您好，我的邮箱是ms_skx@163.com，您把联系方式发过来我添加您
